version: "3.8"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trpc
volumes:
  dbdata: